version: "3.9"
services:
  backend:
    build: ./backend/
    env_file:
      - ./backend/login.env
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    depends_on: [backend]
